#!/usr/bin/env -S deno run --no-check --allow-run --allow-read
import { command, pre, runCommand, args } from 'https://raw.githubusercontent.com/sagea/deno-utilities/main/command-runners.ts';

pre('build', 'build:watch') `
  ./scripts clean
  ./scripts copy-files
`

command('clean') `
  rm -rf build/
  mkdir build/
  mkdir build/src/
`

command('copy-files') `
  cp -r sprites/ build/sprites;
  cp index_template.html ./build/index.html;
`

command('build') `
echo "starting build"
(
  trap 'kill 0' SIGINT;
  deno bundle --import-map=import_maps.json --no-check src/loader.ts build/src/loader.js &
  deno bundle --import-map=import_maps.json --no-check ./src/app-worker.ts build/src/app-worker.js &
  deno bundle --import-map=import_maps.json --no-check ./src/canvas-worker.ts build/src/canvas-worker.js &
  wait
)
`;

command('build:watch') `
(
  trap 'kill 0' SIGINT;
  deno bundle --watch --import-map=import_maps.json --no-check src/loader.ts build/src/loader.js &
  deno bundle --watch --import-map=import_maps.json --no-check ./src/app-worker.ts build/src/app-worker.js &
  deno bundle --watch --import-map=import_maps.json --no-check ./src/canvas-worker.ts build/src/canvas-worker.js &
  wait
)
`;

command('dev-server') `
(
  trap 'kill 0' SIGINT;
  deno run --allow-net --allow-read ./dev-server.ts
)
`;

command('dev') `
(
  trap 'kill 0' SIGINT;
  ./scripts build:watch &
  ./scripts dev-server &
  wait
)
`
command('test') `
  deno test --import-map=import_maps.json --no-check ${args(Deno.args.slice(1))} src/
`

runCommand(Deno.args);



