import { immutable } from '../generics/mod.ts';

export const NativeKeyCodes = immutable({
  AltLeft: 'AltLeft',
  AltRight: 'AltRight',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ArrowUp: 'ArrowUp',
  Backquote: 'Backquote',
  Backslash: 'Backslash',
  Backspace: 'Backspace',
  BracketLeft: 'BracketLeft',
  BracketRight: 'BracketRight',
  CapsLock: 'CapsLock',
  Comma: 'Comma',
  ControlLeft: 'ControlLeft',
  Digit0: 'Digit0',
  Digit1: 'Digit1',
  Digit2: 'Digit2',
  Digit3: 'Digit3',
  Digit4: 'Digit4',
  Digit5: 'Digit5',
  Digit6: 'Digit6',
  Digit7: 'Digit7',
  Digit8: 'Digit8',
  Digit9: 'Digit9',
  Enter: 'Enter',
  Equal: 'Equal',
  Escape: 'Escape',
  KeyA: 'KeyA',
  KeyB: 'KeyB',
  KeyC: 'KeyC',
  KeyD: 'KeyD',
  KeyE: 'KeyE',
  KeyF: 'KeyF',
  KeyG: 'KeyG',
  KeyH: 'KeyH',
  KeyI: 'KeyI',
  KeyJ: 'KeyJ',
  KeyK: 'KeyK',
  KeyL: 'KeyL',
  KeyM: 'KeyM',
  KeyN: 'KeyN',
  KeyO: 'KeyO',
  KeyP: 'KeyP',
  KeyQ: 'KeyQ',
  KeyR: 'KeyR',
  KeyS: 'KeyS',
  KeyT: 'KeyT',
  KeyU: 'KeyU',
  KeyV: 'KeyV',
  KeyW: 'KeyW',
  KeyX: 'KeyX',
  KeyY: 'KeyY',
  KeyZ: 'KeyZ',
  MetaLeft: 'MetaLeft',
  MetaRight: 'MetaRight',
  Minus: 'Minus',
  Period: 'Period',
  Quote: 'Quote',
  Semicolon: 'Semicolon',
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  Slash: 'Slash',
  Space: 'Space',
  Tab: 'Tab',
} as const);

export const AliasKeyCodes = immutable({
  'Shift': ['ShiftLeft', 'ShiftRight'],
  'Meta': ['MetaLeft', 'MetaRight'],
  'Alt': ['AltLeft', 'AltRight'],
} as const);

export const KeyCodes = immutable({ ...NativeKeyCodes, ...AliasKeyCodes });
export type NativeKeyCode = keyof typeof NativeKeyCodes;
